# Generated by Django 5.0.5 on 2024-05-08 13:12

import onetomultipleimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomultipleimage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='sizes',
            field=onetomultipleimage.models.ListCharField(default='', max_length=255, verbose_name='sizes'),
            preserve_default=False,
        ),
    ]
