# Generated by Django 5.0.5 on 2024-05-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomultipleimage', '0002_image_sizes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='FatherImage',
        ),
    ]
