# Generated by Django 5.0.5 on 2024-05-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomultipleimage', '0003_rename_image_fatherimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesizes',
            name='father',
        ),
        migrations.DeleteModel(
            name='FatherImage',
        ),
        migrations.DeleteModel(
            name='ImageSizes',
        ),
    ]
