# Generated by Django 5.0.5 on 2024-05-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetomultipleimage', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fatherimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='imagesizes',
            table=None,
        ),
    ]
